<?php

require_once("./utils.php");

/**
 * This script will generate the unique api key to manage the applications and its related activities such as following
 * 1. Create/Update/Delete Applications
 * 2. View Request Stats
 * 3. Add/Remove Domains & IP to Whitelist for application
 * 4. for any other up-coming admin related stuff.
 *
 * The Key is generated by based on the server information which will be unqiue.
 */

use Helpers\Utils;

$ip = $_SERVER["REMOTE_ADDR"];
$key = Utils::encryptText("G-PHP-BaaS-$ip");

echo "<span style='font-family: verdana; font-size: 12px'><b>Please use the below key in your admin api header e.g. x-api-key: $key </b></span><br/><br/>";
echo "<span style='font-family: verdana; font-size: 12px'><b>$key</b></span>";
